version: '3'
services:
  pydocinter:
    build:
      context: .
      dockerfile: ./Dockerfile 
    container_name: pydocinter
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: pydocinter
      SERVICE_TAGS: dev
    working_dir: /content
    volumes:
      - ./:/content
      - /tmp:/tmp
    networks:
      - python-machinelearning-network
networks:
  python-machinelearning-network:
    driver: bridge
